package vue;

import controller.ControllerAccepter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class VueAjoutChambre extends JPanel{
    VueHotel main;
    JTextField etage;
    JTextField prixEuro;
    JComboBox<String> listeTypeChambre;
    ButtonGroup minibar;
    JRadioButton hasMinibar;
    JRadioButton hasNoMinibar;
    JButton confirmer;

    public VueAjoutChambre(VueHotel main){
        super(new BorderLayout(3,3));
        this.main = main;
        JLabel titre = new JLabel("Ajouter Chambre");
        titre.setHorizontalAlignment(SwingConstants.CENTER);
        this.add(titre, BorderLayout.NORTH);
        JPanel formulaire = new JPanel(new GridLayout(4,2, 3, 3));
        JLabel etageL = new JLabel("Saisir étage : ");
        formulaire.add(etageL);
        JPanel etagePanel = new JPanel(new BorderLayout());
        etage = new JTextField();
        etagePanel.add(etage, BorderLayout.CENTER);
        JLabel etageEltManquant = new JLabel();
        etageEltManquant.setForeground(Color.RED);
        etagePanel.add(etageEltManquant, BorderLayout.SOUTH);
        formulaire.add(etagePanel);
        JPanel argent = new JPanel(new BorderLayout());
        JLabel prixEuroL = new JLabel("Saisir prix chambre : ");
        formulaire.add(prixEuroL);
        prixEuro = new JTextField();
        argent.add(prixEuro, BorderLayout.CENTER);
        JLabel euroL = new JLabel("€/nuit");
        argent.add(euroL, BorderLayout.EAST);
        JLabel prixEltManquant = new JLabel();
        prixEltManquant.setForeground(Color.red);
        argent.add(prixEltManquant, BorderLayout.SOUTH);
        formulaire.add(argent);
        JLabel typeChambreL = new JLabel("Saisir type chambre :");
        Vector<String> listeType = new Vector<>();
        listeType.add("Simple");
        listeType.add("Double");
        listeType.add("Suite Normale");
        listeType.add("Suite Présidentielle");
        listeTypeChambre = new JComboBox<>(listeType);
        formulaire.add(typeChambreL);
        formulaire.add(listeTypeChambre); 
        JLabel minibarL = new JLabel("La chambre possède un minibar : ");
        minibar = new ButtonGroup();
        hasMinibar = new JRadioButton("Oui");
        hasNoMinibar = new JRadioButton("Non");
        hasNoMinibar.setSelected(true);
        minibar.add(hasMinibar);
        minibar.add(hasNoMinibar);
        formulaire.add(minibarL);
        JPanel radioButtons = new JPanel(new BorderLayout());
        radioButtons.add(hasMinibar, BorderLayout.WEST);
        radioButtons.add(hasNoMinibar, BorderLayout.EAST);
        formulaire.add(radioButtons);
        this.add(formulaire, BorderLayout.CENTER);
        confirmer = new JButton("Ajouter chambre");
        confirmer.setBackground(Color.green);
        Vector<JTextField> listFields = new Vector<JTextField>();
        listFields.add(etage);
        listFields.add(prixEuro);
        Vector<JLabel> listLabels = new Vector<JLabel>();
        listLabels.add(etageEltManquant);
        listLabels.add(prixEltManquant);
        confirmer.addActionListener(new ControllerAccepter(main, listFields, listLabels, hasNoMinibar, listeTypeChambre));
        this.add(confirmer, BorderLayout.SOUTH);
    }
}
